server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  config:
    import: "optional:file:.env[.properties]"

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10


tmdb:
  access-token: ${TMDB_ACCESS_TOKEN}
  base-image-url: ${TMDB_BASE_IMAGE_URL}

custom:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    # 접근 토큰 유효기간(초)
    access-expire-seconds: "#{300}"
    # 리프레시 토큰 유효기간(일)
    refresh-expire-days: "#{7}"